version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - localexp
  go:
    image: golang:1.5
    ports:
      - 8081:8081
    networks:
      - localexp
  grafana:
    image: grafana/grafana
    env_file:
      - ./config.monitoring
    ports:
      - 3000:3000
    networks:
      - localexp
networks:
  localexp:
    driver: bridge