name: build

on:
  push:
    tags:
      - 'V*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Meta
      id: meta
      with:
        images: filstimatias/bari
        tags: | 
          type=semver,pattern={{version}}
    - name: build and push to docker
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: filstimatias/bari
        tags: ${{ steps.meta.outputs.tags }}