name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        #GH_TOKEN: ${{ secrets.PAT_TOKEN_WORKFLOW }}
    - name: build and push to docker
      uses: docker/build-push-action@v5
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: filstimatias/bari
        #tag_with_ref: true
        #tag_with_sha: true
        tags: ${{ env.RELEASE_VERSION }}