name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.1

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.57
      args: --timeout=30m --issues-exit-code=1
    #- name: Install golint
    #  run: go install golang.org/x/lint/golint@latest

    #- name: Run golint
    #  run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...